version: '3.2'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - 1433:1433
    volumes: 
      - ./sqldata:/var/opt/mssql/
      - ./sqllog:/var/opt/sqlserver/log

  nginx:
    image: tiangolo/nginx-rtmp:latest
    ports:
      - 80:80
      - 1935:1935
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/usr/share/nginx/html


  