services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
      - ./videos:/var/www/videos
  php:
    image: php:8.3-fpm
    volumes:
      - ./php:/var/www/html
      - ./data:/var/www/data