worker_processes auto;
rtmp_auto_push on;

events {}

# -------------------------
# HTTP SERVER (PORT 80)
# -------------------------
http {
    server {
        listen 80;
        listen [::]:80;

        server_name localhost;

        root /var/www/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}

# -------------------------
# RTMP SERVER (PORT 1935)
# -------------------------
rtmp {
    server {
        listen 1935;
        listen [::]:1935 ipv6only=on;

        application live {
            live on;
            record off;
        }
    }
}